---
- id: snykio:go:k8s.io/kubernetes/pkg/apiserver:174807
  title: Access Restriction Bypass
  description: |
    [k8s.io/kubernetes/pkg/apiserver][1] is a Production-Grade Container
    Scheduling and Management.

    Affected versions of this package are vulnerable to Access Restriction
    Bypass. The API server in Kubernetes does not properly check admission
    control, which allows remote authenticated users to access additional
    resources via a crafted patched object.



    [1]: https://kubernetes.io
  affected_package: k8s.io/kubernetes/pkg/apiserver
  vulnerable_versions:
  - "<1.2.0-alpha.6"
  severity: high
  package_manager: go
  cve:
  - CVE-2016-1905
  cwe:
  - CWE-284
  disclosed_date: 2016-02-03
  created_date: 2016-03-02
  last_modified_date: 2016-03-02
  credit:
  - Unknown
  references:
  - https://access.redhat.com/errata/RHSA-2016:0070
  - https://github.com/kubernetes/kubernetes/commit/9e6912384a5bc714f2a780b870944a8cee264a22
  - https://github.com/kubernetes/kubernetes/issues/19479
  source_url: https://snyk.io/vuln/SNYK-GOLANG-K8SIOKUBERNETESPKGAPISERVER-174807
