---
- id: snykio:npm:eslint-config-airbnb-standard:20180712
  title: Malicious Package
  description: |
    [`eslint-config-airbnb-standard`][1] extends ESLint with airbnb and
    standard configs.

    Versions 2.0.0, 2.1.0 and 2.1.1 were identified as malicious after a
    possible npm account takeover. During installation, the malicious code
    download code from `pastebin.com`, then executed it. It sent the
    contents of the userâ€™s `.npmrc` file to the attacker, which typically
    contains access tokens for publishing to npm.

    The malicious package versions have been unpublished from npm.



    [1]: https://www.npmjs.com/package/eslint-config-airbnb-standard
  affected_package: eslint-config-airbnb-standard
  vulnerable_versions:
  - ">=2.0.0 <2.1.2"
  severity: high
  package_manager: npm
  cwe:
  - CWE-506
  disclosed_date: 2018-07-12
  created_date: 2018-07-13
  last_modified_date: 2018-07-13
  credit:
  - Unknown
  references:
  - https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes
  - https://github.com/doasync/eslint-config-airbnb-standard/issues/3
  - https://github.com/eslint/eslint-scope/issues/39
  source_url: https://snyk.io/vuln/npm:eslint-config-airbnb-standard:20180712
