---
- id: ossindex:npm:fury-adapter-swagger:2017-07-29
  title: Directory Traversal
  description: "> [The package] has a vulnerability that allows arbitrary file reads
    off the file system. This could be used to retrieve sensitive data, or cause a
    denial of service by reading /dev/zero.\n> \n> -- [nodesecurity.io](https://nodesecurity.io/advisories/305)"
  affected_package: fury-adapter-swagger
  vulnerable_versions:
  - ">=0.2.0 <=0.9.7"
  package_manager: npm
  disclosed_date: 2017-07-29
  created_date: 2017-07-29
  last_modified_date: 2017-07-30
  credit:
  - OSSIndex
  references:
  - http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-1000249
  - https://github.com/distributedweaknessfiling/DWF-Database-Artifacts/blob/master/DWF/2016/1000249/CVE-2016-1000249.json
  - https://nodesecurity.io/advisories/305
  source_url: https://ossindex.net/resource/package/8321077215/vulnerabilities
- id: snykio:npm:fury-adapter-swagger:CVE-2016-1000249
  title: Directory Traversal
  description: |
    [`fury-adapter-swagger`][1] is Swagger 2.0 parser for Fury.js.
    [`Fury`][2] is an SDK that helps loading and HTTP API description format
    (like [`swagger`][3]) and creates a uniformed format which is easy to
    work with. The swagger description document is a JSON or YAML file and
    per specification allows inclusion of other documents by reference. Fury
    takes this JSON file and outputs it as a JS object. This may allow any
    user and in particular a malicious user to edit the swagger document in
    an online editor and write and file into it\'s references, and in
    particular any file on the applications hosting server (e.g.
    `/etc/passwrd`). The document will try to include the contents of the
    referenced file during parsing and may expose confidential information
    like passwords, environment variables, DB Connection credentials, etc.
    Also, a possible Denial of service may occur due to `/dev/zero`
    consuming all available memory.

    Thanks to [Adam Kliment][4] and [Honza Javorek][5] for finding and
    reporting this vulnerability to us.



    [1]: https://www.npmjs.com/package/fury-adapter-swagger
    [2]: https://github.com/apiaryio/fury.js/
    [3]: http://swagger.io/
    [4]: https://github.com/netmilk
    [5]: https://github.com/honzajavorek
    \nA Directory Traversal attack (also known as path traversal) aims to
    access files and directories that are stored outside the intended
    folder. By manipulating files with \"dot-dot-slash (../)\" sequences and
    its variations, or by using absolute file paths, it may be possible to
    access arbitrary files and directories stored on file system, including
    application source code, configuration, and other critical system files.

    Directory Traversal vulnerabilities can be generally divided into two
    types:

    * **Information Disclosure**\: Allows the attacker to gain information
      about the folder structure or read the contents of sensitive files on
      the system.

    `st` is a module for serving static files on web pages, and contains a
    [vulnerability of this type][1]. In our example, we will serve files
    from the `public` route.

    If an attacker requests the following URL from our server, it will in
    turn leak the sensitive private key of the root user.

        curl http://localhost:8080/public/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/root/.ssh/id_rsa

    **Note** `%2e` is the URL encoded version of `.` (dot).

    * **Writing arbitrary files**\: Allows the attacker to create or replace
      existing files. This type of vulnerability is also known as
      `Zip-Slip`.

    One way to achieve this is by using a malicious `zip` archive that holds
    path traversal filenames. When each filename in the zip archive gets
    concatenated to the target extraction folder, without validation, the
    final path ends up outside of the target folder. If an executable or a
    configuration file is overwritten with a file containing malicious code,
    the problem can turn into an arbitrary code execution issue quite
    easily.

    The following is an example of a `zip` archive with one benign file and
    one malicious file. Extracting the malicious file will result in
    traversing out of the target folder, ending up in `/root/.ssh/`
    overwriting the `authorized_keys` file:

        2018-04-15 22:04:29 .....           19           19  good.txt
        2018-04-15 22:04:42 .....           20           20  ../../../../../../root/.ssh/authorized_keys



    [1]: https://snyk.io/vuln/npm:st:20140206
  affected_package: fury-adapter-swagger
  vulnerable_versions:
  - "<0.9.7 >=0.2.0"
  - "~0.8.0-pre"
  severity: high
  package_manager: npm
  cve:
  - CVE-2016-1000249
  cwe:
  - CWE-22
  disclosed_date: 2016-10-23
  created_date: 2017-01-11
  last_modified_date: 2017-01-11
  credit:
  - Adam Kliment
  references:
  - https://github.com/apiaryio/fury-adapter-swagger/commit/777e2d68f03546a88f3203bbd4725df8b1f662a7
  - https://github.com/distributedweaknessfiling/DWF-Database-Artifacts/blob/master/DWF/2016/1000249/CVE-2016-1000249.json
  source_url: https://snyk.io/vuln/npm:fury-adapter-swagger:20161024
