---
- id: npmjs:npm:restify-swagger-jsdoc:1037
  title: Path Traversal
  description: "Versions of `restify-swagger-jsdoc` prior to 3.2.1 are vulnerable
    to Path Traversal.  The package fails to properly sanitize URLs, which may allow
    attackers to access server files outside the `swagger-ui` folder by using relative
    paths.  \n"
  affected_package: restify-swagger-jsdoc
  vulnerable_versions:
  - "<3.2.1"
  severity: high
  package_manager: npm
  cwe: CWE-22
  disclosed_date: 1970-01-01
  created_date: 1970-01-01
  last_modified_date: 1970-01-01
  credit: xylesoft
  references: https://npmjs.com/advisories/1037
  source_url: https://npmjs.com/advisories/1037
- id: snykio:npm:restify-swagger-jsdoc:451631
  title: Directory Traversal
  description: |
    [restify-swagger-jsdoc][1] is a package that creates Swagger
    documentation page based on jsdoc.

    Affected versions of this package are vulnerable to Directory Traversal.
    The package fails to properly sanitize URLs, which may allow attackers
    to access server files outside the `swagger-ui` folder by using relative
    paths.



    [1]: https://www.npmjs.com/package/restify-swagger-jsdoc
  affected_package: restify-swagger-jsdoc
  vulnerable_versions:
  - "<3.2.1"
  severity: high
  package_manager: npm
  cwe:
  - CWE-22
  disclosed_date: 2019-07-03
  created_date: 2019-07-16
  last_modified_date: 2019-07-16
  credit:
  - xylesoft
  references:
  - https://github.com/RemyJeancolas/restify-swagger-jsdoc/commit/52abae36aaf2c4147c25da7ac3698fe722f2d119
  - https://github.com/RemyJeancolas/restify-swagger-jsdoc/issues/23
  source_url: https://snyk.io/vuln/SNYK-JS-RESTIFYSWAGGERJSDOC-451631
