---
- id: npmjs:npm:sj-tw-test-security:1308
  title: Malicious Package
  description: All versions of `sj-tw-test-security` contain malicious code. The package
    downloads and runs a script that opens a reverse shell in the system.
  affected_package: sj-tw-test-security
  vulnerable_versions:
  - ">=0.0.0"
  severity: high
  package_manager: npm
  cwe: CWE-506
  disclosed_date: 1970-01-01
  created_date: 1970-01-01
  last_modified_date: 1970-01-01
  credit: Microsoft Vulnerability Research
  references: https://npmjs.com/advisories/1308
  source_url: https://npmjs.com/advisories/1308
- id: snykio:npm:sj-tw-test-security:480452
  title: Malicious Package
  description: |
    [sj-tw-test-security][1] is a malicious package.

    This package downloads and runs a script that opens a reverse shell in
    the system.



    [1]: https://libraries.io/npm/sj-tw-test-security
  affected_package: sj-tw-test-security
  vulnerable_versions:
  - "*"
  severity: high
  package_manager: npm
  cwe:
  - CWE-506
  disclosed_date: 2019-11-07
  created_date: 2019-11-07
  last_modified_date: 2019-11-07
  credit:
  - Microsoft Vulnerability Research
  references:
  - https://www.npmjs.com/advisories/1308
  - https://www.npmjs.com/advisories/1309
  - https://www.npmjs.com/advisories/1310
  source_url: https://snyk.io/vuln/SNYK-JS-SJTWTESTSECURITY-480452
