---
- id: snykio:maven:org.neo4j:neo4j-security:31600
  title: Timing Attack
  description: |
    [`org.neo4j:neo4j-security`][1] is the worldâ€™s leading Graph Database.
    It is a high performance graph store with all the features expected of a
    mature and robust database, like a friendly query language and ACID
    transactions.

    Affected versions of the package are vulnerable to Timing Attack due to
    using the `Arrays.equals` to validate the password, which is vulnerable
    to a brute force attacks by malicious users.



    [1]: https://neo4j.org
  affected_package: org.neo4j:neo4j-security
  vulnerable_versions:
  - "< 3.0.12"
  severity: medium
  package_manager: maven
  cwe:
  - CWE-310
  disclosed_date: 2017-09-26
  created_date: 2017-11-29
  last_modified_date: 2017-11-29
  credit:
  - Unknown
  references:
  - https://github.com/neo4j/neo4j/commit/cad758138c1ab49303230312034564abe0fe57fa
  - https://github.com/neo4j/neo4j/pull/10158
  source_url: https://snyk.io/vuln/SNYK-JAVA-ORGNEO4J-31600
