---
- id: snykio:go:github.com/docker/libcontainer:50012
  title: Symlink Attack
  description: |
    Affected version of [`github.com/docker/libcontainer`][1] are vulnerable
    to Symlink Attacks. Libcontainer and Docker Engine before 1.6.1 opens
    the file-descriptor passed to the pid-1 process before performing the
    chroot, which allows local users to gain privileges via a symlink attack
    in an image.



    [1]: https://github.com/docker/libcontainer
  affected_package: github.com/docker/libcontainer
  vulnerable_versions:
  - "<1.6.1"
  severity: high
  package_manager: go
  cve:
  - CVE-2015-3627
  cwe:
  - CWE-59
  disclosed_date: 2015-08-06
  created_date: 2015-08-06
  last_modified_date: 2015-08-06
  credit:
  - TÃµnis Tiigi
  references:
  - http://packetstormsecurity.com/files/131835/Docker-Privilege-Escalation-Information-Disclosure.html
  - http://seclists.org/fulldisclosure/2015/May/28
  - https://github.com/docker/libcontainer/commit/46132cebcf391b56842f5cf9b247d508c59bc625
  - https://groups.google.com/forum/#%21searchin/docker-user/1.6.1/docker-user/47GZrihtr-4/nwgeOOFLexIJ
  - https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-3627
  source_url: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMDOCKERLIBCONTAINER-50012
