---
- id: snykio:go:github.com/ipfs/go-ipfs/repo/config:50058
  title: Man-in-the-Middle (MitM)
  description: |
    Affected versions of [`github.com/ipfs/go-ipfs/repo/config`][1] are
    vulnerable to Man-in-the-Middle (MitM) attacks, as it does not encrypt
    the private key.

    You can read more about `Man-in-the-Middle (MitM)` on our [blog][2].



    [1]: https://github.com/ipfs/go-ipfs/tree/master/repo/config
    [2]: https://snyk.io/blog/https-breaking-through/
  affected_package: github.com/ipfs/go-ipfs/repo/config
  vulnerable_versions:
  - "*"
  severity: medium
  package_manager: go
  cwe:
  - CWE-300
  disclosed_date: 2014-09-19
  created_date: 2018-01-10
  last_modified_date: 2018-01-10
  credit:
  - Unknown
  references:
  - https://github.com/ipfs/go-ipfs/commit/e57275f3d20767c90766e3369e0d0a38273fbba9
  - https://github.com/ipfs/go-ipfs/issues/92
  source_url: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMIPFSGOIPFSREPOCONFIG-50058
